define: DUK_USE_JSON_STRINGIFY_FASTPATH
introduced: 1.3.0
default: false
tags:
  - performance
  - fastpath
  - lowmemory
description: >
  Enable fast path for JSON.stringify() serialization.  The fast path is used
  when there is no "replacer" or indent; in practice, when JSON.stringify() is
  called with only a value argument.  The fast path increases code footprint by
  roughly 1.5 kB but is up to 4-5x faster than the slow path.
