# Base configuration for performance sensitive environments, see
# doc/performance-sensitive.rst.

# You should choose the fastest setjmp/longjmp for your platform.

DUK_USE_FASTINT: true
DUK_USE_VALSTACK_UNSAFE: true
DUK_USE_FAST_REFCOUNT_DEFAULT: true
DUK_USE_JSON_STRINGIFY_FASTPATH: true  # not fully portable right now
DUK_USE_JSON_QUOTESTRING_FASTPATH: true
DUK_USE_JSON_DECSTRING_FASTPATH: true
DUK_USE_JSON_DECNUMBER_FASTPATH: true
DUK_USE_JSON_EATWHITE_FASTPATH: true
DUK_USE_INTERRUPT_COUNTER: false
DUK_USE_DEBUGGER_SUPPORT: false
